version: '3'

services:
  flask-app:
    image: 'flask-app'
    ports:
      - '5000:5000'
    depends_on:
      - postgresql
    environment:
      - FLASK_ENV=DEVELOPMENT_DOCKER
      - DB_HOST=postgresql
      - DB_USER=dev
      - DB_PASS=dev
      - DB_NAME=dev
      - DB_PORT=5432
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
